title = "Menu Title"
type = "GENERIC_9x1"
open-command = ["menu"]
open-actions = []
close-actions = []

[[open-requirements]]
expression = """
    $hasPermission('server.admin')
    && %player_balance% >= 199
"""
deny-actions = ["[MESSAGE] <red>Access denied."]

[[items]]
material = "DIAMOND"
render-priority = 1
display-name = "<yellow>Click to buy this diamond"
slots = [5]
lore = []
view-requirements = "$hasPermission('shop.see.diamond')"

[[items.actions]]
type = "left_click"

[[items.actions.requirements]]
expression = "%player_balance% >= 1000"
deny-actions = ["[MESSAGE] <red> Not enough money."]
